AWSTemplateFormatVersion: '2010-09-09'
Description: Seller-side template for WakimWorks S3 Security Scanner - Central resources for scanning client accounts.

Parameters:
  LambdaCodeS3Bucket:
    Type: String
    Description: S3 bucket name containing the Lambda code zip (in your account).
    Default: judewakim-s3-misconfig
  LambdaCodeS3Key:
    Type: String
    Description: S3 key for the Lambda code zip (e.g., code/s3-misconfig.zip).
    Default: code/s3-misconfig.zip
  SenderEmail:
    Type: String
    Description: Verified SES sender email (e.g., scanner@wakimworks.com).
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
    Default: scanner@wakimworks.com

Resources:
  # DynamoDB Table for Client Metadata
  ClientMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: S3ScannerClientMetadata
      AttributeDefinitions:
        - AttributeName: AccountId
          AttributeType: S
      KeySchema:
        - AttributeName: AccountId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST  # On-demand for MVP

  # SQS Queue for Registrations
  RegistrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: S3ScannerRegistrationQueue
      VisibilityTimeout: 360  # Must be >= Lambda timeout (300s) + buffer
      MessageRetentionPeriod: 1209600  # 14 days, adjust as needed
      ReceiveMessageWaitTimeSeconds: 0  # No long polling for Lambda
      DelaySeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  # SQS Queue Policy for Cross-Account Access
  RegistrationQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref RegistrationQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: sqs:SendMessage
            Resource: !GetAtt RegistrationQueue.Arn
          - Effect: Allow
            Principal: '*'  # Broad for MVP; tighten to specific client account IDs later
            Action: sqs:SendMessage
            Resource: !GetAtt RegistrationQueue.Arn

  # Dead Letter Queue
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: S3ScannerRegistrationDLQ

  # Lambda to Process SQS Registrations
  RegistrationProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: S3ScannerRegistrationProcessor
      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt RegistrationProcessorRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          from datetime import datetime
          import logging

          # Set up logging
          logging.basicConfig(level=logging.INFO)
          logger = logging.getLogger(__name__)

          def handler(event, context):
              try:
                  # Initialize clients
                  dynamodb = boto3.resource('dynamodb', region_name='us-east-1')
                  sqs = boto3.client('sqs', region_name='us-east-1')
                  table = dynamodb.Table(os.environ['DYNAMODB_TABLE'])
                  queue_url = os.environ['SQS_QUEUE_URL']

                  results = []
                  for record in event['Records']:
                      try:
                          payload = json.loads(record['body'])
                          action = payload.get('Action')
                          account_id = payload.get('AccountId')

                          if action == 'register':
                              table.put_item(
                                  Item={
                                      'AccountId': payload['AccountId'],
                                      'RoleArn': payload['RoleArn'],
                                      'Email': payload['Email'],
                                      'InvocationMode': payload['InvocationMode'],
                                      'ExcludeBuckets': payload['ExcludeBuckets'],
                                      'ExternalId': payload['ExternalId'],
                                      'RegisteredAt': datetime.utcnow().isoformat()
                                  }
                              )
                              logger.info(f"Wrote to DynamoDB: AccountId={account_id}")
                              results.append({'account_id': account_id, 'status': 'registered'})
                          elif action == 'deregister':
                              table.delete_item(Key={'AccountId': account_id})
                              logger.info(f"Deleted from DynamoDB: AccountId={account_id}")
                              results.append({'account_id': account_id, 'status': 'deregistered'})
                          else:
                              logger.warning(f"Skipping unknown action: {action} for AccountId={account_id}")
                              results.append({'account_id': account_id, 'status': 'skipped', 'reason': f"Unknown action: {action}"})

                          # Delete SQS message
                          sqs.delete_message(
                              QueueUrl=queue_url,
                              ReceiptHandle=record['receiptHandle']
                          )
                          logger.info(f"Deleted SQS message for AccountId={account_id}, Action={action}")

                      except Exception as e:
                          logger.error(f"Error processing message for AccountId={account_id}, Action={action}: {str(e)}")
                          results.append({'account_id': account_id, 'status': 'error', 'reason': str(e)})
                          # Continue to next message to avoid blocking

                  return {'status': 'Processed', 'results': results}

              except Exception as e:
                  logger.error(f"Error in handler: {str(e)}")
                  raise
      Timeout: 60
      MemorySize: 128
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref ClientMetadataTable
          SQS_QUEUE_URL: !GetAtt RegistrationQueue.QueueUrl

  # Event Source Mapping for SQS to Processor Lambda
  SqsEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt RegistrationQueue.Arn
      FunctionName: !GetAtt RegistrationProcessorLambda.Arn
      Enabled: true
      BatchSize: 1
      MaximumBatchingWindowInSeconds: 0

  # IAM Role for Registration Processor
  RegistrationProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:deleteItem
                Resource: !GetAtt ClientMetadataTable.Arn
        - PolicyName: SqsProcessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt RegistrationQueue.Arn

  # Main Scanner Lambda
  ScannerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: S3SecurityScanner
      Handler: s3-misconfig.lambda_handler  # From your py file
      Runtime: python3.12
      Role: !GetAtt ScannerLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
      Timeout: 300  # Longer for potential multi-tenant
      MemorySize: 256
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref ClientMetadataTable
          SENDER_EMAIL: !Ref SenderEmail

  # IAM Role for Scanner Lambda
  ScannerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3SecurityScannerLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ScannerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:GetItem
                Resource: !GetAtt ClientMetadataTable.Arn
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: '*'  # Client roles; scope with conditions if needed
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: "*"
              - Effect: Allow
                Action: 
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                Resource: !GetAtt RegistrationQueue.Arn

  # SQS Trigger for Immediate Scans
  ScannerSqsTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt RegistrationQueue.Arn
      FunctionName: !GetAtt ScannerLambda.Arn
      Enabled: true
      BatchSize: 1
      MaximumBatchingWindowInSeconds: 0

  # EventBridge Rule for Daily Scans
  DailyScanRule:
    Type: AWS::Events::Rule
    Properties:
      Name: S3SecurityScannerDaily
      ScheduleExpression: cron(0 2 * * ? *)  # 10 PM EDT (2 AM UTC)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ScannerLambda.Arn
          Id: ScannerTarget
          Input: '{"mode": "daily_scan"}'  # Lambda will query DynamoDB

  # Permission for EventBridge to Invoke Scanner Lambda
  EventBridgeInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ScannerLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyScanRule.Arn

Outputs:
  RegistrationQueueUrl:
    Description: URL of the SQS queue for client registrations (share with clients).
    Value: !Ref RegistrationQueue
  ScannerLambdaArn:
    Description: ARN of the scanner Lambda.
    Value: !GetAtt ScannerLambda.Arn
  ClientMetadataTableName:
    Description: Name of the DynamoDB table.
    Value: !Ref ClientMetadataTable