AWSTemplateFormatVersion: "2010-09-09"
Description: >
  WakimWorks S3 Scanner Launcher:
  - Creates IAM role for EC2 instance
  - Launches EC2 instance from AMI
  - Passes user parameters to AMI user-data script

Parameters:
  ExcludeBuckets:
    Type: String
    Description: "Comma-separated list of S3 bucket names (e.g., bucket1,bucket2)"
    Default: ""
  InvocationMode:
    Type: String
    Description: "Choose the EventBridge invocation mode: 'scanning_only' or 'scanning_and_autoremediation'"
    Default: "scanning_only"
    AllowedValues:
      - "scanning_only"
      - "scanning_and_autoremediation"
  UserEmail:
    Type: String
    Description: "Email to receive scan notifications"
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
    ConstraintDescription: Must be a valid email address
  AMIId:
    Type: AWS::EC2::Image::Id
    Description: "AMI ID to be used for launching the EC2 instance"
    Default: ami-022919def8d680c1d

Resources:
  # ------------------------------
  # IAM Role for EC2 Instance
  # ------------------------------
  S3ScannerLauncherRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3ScannerLauncherRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ScannerLauncherPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CloudFormationStackManagement
                Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ListStacks
                  - cloudformation:ListStackResources
                  - cloudformation:DeleteStack
                Resource: "*"

              - Sid: IAMRoleAndPolicyCreation
                Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:PutRolePolicy
                  - iam:PassRole
                  - iam:TagRole
                  - iam:GetRole
                  - iam:DeleteRolePolicy
                  - iam:DeleteRole
                  - iam:DetachRolePolicy
                  - iam:DetachRole
                Resource: "arn:aws:iam::*:role/S3SecurityScannerRole*"

              - Sid: LambdaManagement
                Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:GetFunction
                  - lambda:DeleteFunction
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:TagResource
                  - lambda:ListFunctions
                  - lambda:GetFunctionConfiguration
                  - lambda:InvokeFunction
                Resource: "arn:aws:lambda:*:*:function:S3SecurityScanner*"

              - Sid: EventBridgeManagement
                Effect: Allow
                Action:
                  - events:PutRule
                  - events:DescribeRule
                  - events:GetRule
                  - events:PutTargets
                Resource: "*"

              - Sid: SNSManagement
                Effect: Allow
                Action:
                  - sns:CreateTopic
                  - sns:Subscribe
                  - sns:Publish
                  - sns:GetTopicAttributes
                  - sns:SetTopicAttributes
                  - sns:TagResource
                Resource: "*"

              - Sid: SESPermissions
                Effect: Allow
                Action:
                  - ses:CreateConfigurationSet
                  - ses:DeleteConfigurationSet
                  - ses:VerifyEmailIdentity
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: "*"

              - Sid: S3ReadTemplate
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - "arn:aws:s3:::judewakim-s3-misconfig/code/*"

              - Sid: TaggingSupport
                Effect: Allow
                Action:
                  - tag:GetResources
                  - tag:TagResources
                  - tag:UntagResources
                Resource: "*"

              - Sid: STSIdentity
                Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: "*"


  # ------------------------------
  # EC2 Instance Profile
  # ------------------------------
  S3ScannerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: S3ScannerLauncherInstanceProfile
      Roles:
        - Ref: S3ScannerLauncherRole

  # ------------------------------
  # EC2 Instance to launch the AMI
  # ------------------------------
  S3ScannerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      IamInstanceProfile: !Ref S3ScannerInstanceProfile
      ImageId: !Ref AMIId  
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xe # show commands and exit on 
          dnf install -y jq awscli  # ensure jq and aws CLI are available

          STACK_NAME="S3ScannerDeployment"
          TEMPLATE_URL="https://s3.amazonaws.com/judewakim-s3-misconfig/code/template.yaml"
          
          REGION="us-east-1" # Hardcoded for marketplace deplyment stability
          echo "Region: $REGION"

          TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
            -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          echo "Token: $TOKEN"

          ROLE_NAME=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
            http://169.254.169.254/latest/meta-data/iam/info | jq -r .InstanceProfileArn)
          echo "Instance Profile: $ROLE_NAME"

          INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
            http://169.254.169.254/latest/meta-data/instance-id)
          echo "Instance ID: $INSTANCE_ID"
          
          # Wait for IAM role credentials to propagate
          sleep 60
          # Validate that IAM role credentials are available
          aws sts get-caller-identity --region "$REGION" || {
            echo "Error: IAM credentials not found. Verify the instance profile is attached properly."
            exit 1
          }

          echo "Launching S3 Scanner stack..."
          aws cloudformation create-stack \
            --stack-name "$STACK_NAME" \
            --template-url "$TEMPLATE_URL" \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --region "$REGION" \
            --parameters \
              ParameterKey=ExcludeBuckets,ParameterValue="${ExcludeBuckets}" \
              ParameterKey=InvocationMode,ParameterValue="${InvocationMode}" \
              ParameterKey=UserEmail,ParameterValue="${UserEmail}"

          aws cloudformation wait stack-create-complete \
            --stack-name "$STACK_NAME" \
            --region "$REGION"

          echo "Stack created successfully. Terminating instance..."
          aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" --region "$REGION"

Outputs:
  IAMRoleName:
    Description: "IAM Role for EC2 instance"
    Value: !Ref S3ScannerLauncherRole
  EC2InstanceId:
    Description: "ID of the launched EC2 instance (will terminate automatically)"
    Value: !Ref S3ScannerInstance
